const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const read = file => fs.readFileSync(path.join(__dirname, '..', file), 'utf8');
const voice = read('static/js/voiceOrb.js');
const workers = read('static/js/voiceOrbWorkers.js');
const html = read('static/index.html');
const sw = read('static/sw.js');

assert.match(voice, /UI_CONTROL_ALLOWLIST = new Set\(\[\s*'open_view:calendar',\s*'close_view:document',\s*'minimize_view:document'/);
assert.match(voice, /client_state: collectClientState\(\)/);
assert.match(voice, /'X-Tz-Offset': String\(tzOffset\)/);
assert.match(voice, /'X-Tz-Name': tzName/);
assert.match(voice, /handleUIControl\(event\)/);
assert.match(voice, /navigator\.mediaDevices\.getUserMedia/);
assert.match(voice, /\/api\/stt\/transcribe/);
assert.match(voice, /\/api\/tts\/synthesize/);
assert.match(voice, /createOscillator\(\)/);
assert.doesNotMatch(voice, /createElement\(['"]iframe['"]\)|postMessage\(|camera|media manifest/iu);
assert.match(voice, /trackWorkerTask\(event\.task\)/);
assert.match(workers, /new EventSource\(`\/api\/agent-tasks\/\$\{encodeURIComponent\(taskId\)\}\/events`\)/);
assert.match(workers, /\/api\/agent-tasks\?session_id=/);
assert.match(workers, /\/cancel`/);
assert.match(workers, /const LABELS = \{ 'pc-codex': 'PC Codex', hermes: 'Hermes', 'vps-codex': 'VPS Codex' \}/);
assert.doesNotMatch(workers, /eval\(|new Function|querySelector\([^'"`]/);
assert.match(html, /<canvas id="voice-orb-canvas"/);
assert.match(html, /id="voice-worker-rail"/);
assert.doesNotMatch(html, /organic-sphere/);
assert.match(sw, /const CACHE_NAME = 'odysseus-v346'/);
assert.match(sw, /'\/static\/js\/voiceOrb\.js'/);
assert.match(sw, /'\/static\/js\/voiceOrbWorkers\.js'/);
